### ISSUE TITLE
Layout issue.

### ISSUE THREAD

**Issue by Ying1986** [kciter/KCFloatingActionButton#19]
When hide -> show -> open, layout is incorrect.
![layoutissue](https://cloud.githubusercontent.com/assets/6648212/13374924/d30d8828-dd9a-11e5-9a1e-09cf2558cc0b.png)

**Comment by madelman** [comment]
The same is happening to me.

It happens because of this commit:

https://github.com/kciter/KCFloatingActionButton/commit/6045bdcfd58456ea03ae5697908cf98cfb0cefff

The exact line that causes the error is:

frame.origin.x = frame.origin.x - titleLabel.frame.size.width - 10

Because frame.origin.x is substracted repeated times, the first time looks good, but after the buttons have an incorrect layout:

![floating](https://cloud.githubusercontent.com/assets/1317930/13400281/5af5e0a6-df07-11e5-91dd-9883128dde24.png)

**Comment by kciter** [comment]
Oh, I'm sorry. I have fixed it quickly.
Later I will further improve it.
Thanks.

**Comment by kciter** [comment]
Solved on 1.3.0 version.
